name: Render Notebook

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Nix
      uses: cachix/install-nix-action@v13
    - name: Set up Python environment with Nix
      run: |
        nix-shell -p python38Packages.pip
        pip install nbconvert
    - name: Convert Notebook to PDF
      run: |
        python -c 'print("HHH")'

